version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bubblebot
      POSTGRES_PASSWORD: bubblebot_dev
      POSTGRES_DB: bubblebot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bubblebot"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bubblebot:bubblebot_dev@db:5432/bubblebot_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./api:/app
      - ./shared:/shared
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - ./shared:/shared
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api

  # Jupyter Notebooks for AI Demos
  jupyter:
    build:
      context: ./api
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./api/notebooks:/app/notebooks
      - ./shared:/shared
    environment:
      - DATABASE_URL=postgresql://bubblebot:bubblebot_dev@db:5432/bubblebot_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
